---
- hosts: all
  tasks:
    - name: open firewall port
      firewalld:
        service: http
        immediate: true
        permanent: true
        state: enabled

    - name: rebooting lin1
      reboot: