---
- hosts: all
  become: true
  
  tasks:
    - name: Changing hostname
      hostname:
        name: {{ hostname_new }}
      
    - name: Reboot VM and waiting for connection.
      reboot:

    - name: Wait for connection after reboot
      wait_for_connection:
        timeout: 900