---
- hosts: all

  tasks:
    - name: Send message
      pushbullet:
        api_key: "{{ pushbullet_api }}"
        device: "OPPO CPH1979"
        title: Test message from {{ ansible_nodename }}
        body: Hostname: "{{ ansible_hostname }} | {{ ansible_os_family }}"