---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    mount_datavolume: /run

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: on_create

  - debug:
      msg: {{ ansible_mounts }}