---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    - name: "postgres_pwd"
      prompt: "Password for postgres service account"
      private: yes

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: on_create

  - name: Present randomly generated password
    debug:
      msg: "{{ postgres_pwd }}"