---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    mount_datavolume: /postgresql_data

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: on_create
  
  - debug: 
      var: "{{ item.mount }}"
    with_items:
    - "{{ ansible_mounts }}"
    set_fact:
      mount_check: false
    when: "{{ item.mount }} != {{ mount_datavolume }}"


  - name: Abort script when volume is not mounted
    meta: end_host
    when: mount_check == false