---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    mount_datavolume: /
    mount_check: false

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: on_create

  - name: Verify if mount is present
    set_fact:
      mount_check: true
    when: item.mount == mount_datavolume
    loop: "{{ ansible_mounts }}"

  - name: Abort script when volume is not mounted
    fail:
      msg: The data volume is not mounted on /postgresql_data. Aborting the Postgres installation.
    when: mount_check == false

  - name: next step
    debug:
      msg: you made it