---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    mount_datavolume: /run #change to /postgresql_data !!!

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: on_create

  - name: Verify if data disk is present
    debug:
      msg: "Installation can not continu because the datamount is not present"
    when: item.mount != mount_datavolume