---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    mount_datavolume: /
    mount_check: false
    postgres_mount_volume: /postgresql_data
    postgres_base_folder: /postgresql_data/data
    postgres_installer: /tmp/vmware-postgres-11.7-3.el7.x86_64.rpm
    postgis_installer: /tmp/vmware-postgres-postgis-extension-11.7-3.el7.x86_64.rpm
    postgres_config: /postgresql_data/data/postgresql.conf
    hba_ip_range: "192.168.4.0/24"

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: always

  - name: Verify if mount is present
    set_fact:
      mount_check: true
    when: item.mount == mount_datavolume
    loop: "{{ ansible_mounts }}"

  - name: Abort script when volume is not mounted
    fail:
      msg: The data volume is not mounted on /postgresql_data. Aborting the Postgres installation.
    when: mount_check == false

  #### START INSTALLING POSTGRES
  - name: Install required packages
    yum:
      name: {{ item }}
      state: present
    with_items:
      - libpq-dev
      - python-psycopg2

  - name: Generate folder structure for database
    file:
      state: directory
      path: "{{ postgres_base_folder}}"

  - name: Copy installer files needed
    copy:
      src: "{{ item }}"
      dest: /tmp/
      remote_src: no
    with_items:
      - "{{ postgres_installer }}"
      - "{{ postgis_installer }}"

  - name: Install base rpm VMware Postgres
    yum:
      name: "{{ postgres_installer }}"
      state: present

  - name: Make postgres user owner of postgres_data volume
    file:
      state: directory
      path: "{{ postgres_mount_volume }}"
      owner: postgres
      group: root
      recurse: yes

  - name: Check if PostgreSQL database is initialized.
    stat:
      path: "{{ postgres_base_folder }}/PG_VERSION"
    register: pgdata_dir_version

  - name: Initialize database with correct data path
    command: "/usr/bin/initdb -D {{ postgres_base_folder }}/"
    become_user: postgres
    when: not pgdata_dir_version.stat.exists

  - name: Generate service file & start Postgres
    copy:
      content: |
                [Unit]
                Description=CBS - PostgreSQL database server
                Documentation=man:postgres(1)
                After=network.target

                [Service]
                Type=forking
                TimeoutSec=120
                User=postgres
                Group=postgres
                
                ExecStart= /usr/bin/pg_ctl -s -D {{ postgres_base_folder }}/ start -w
                ExecReload=/usr/bin/pg_ctl -s -D {{ postgres_base_folder }}/ reload
                ExecStop=  /usr/bin/pg_ctl -s -D {{ postgres_base_folder }}/ stop -m fast
                
                # Due to PostgreSQL's use of shared memory, OOM killer is often overzealous in
                # killing Postgres, so adjust it downward
                OOMScoreAdjust=-200

                [Install]
                WantedBy=multi-user.target
      dest: /etc/systemd/system/postgresql.service

  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive

  - name: Enable Postgres service
    systemd:
      name: postgresql
      enabled: yes
      daemon_reload: yes

  - name: add new configuration to "postgresql.conf"
    blockinfile:
      dest: "{{ postgres_config }}"
      block: |
        include 'server.conf'

  - name: add new configuration to "server.conf"
    blockinfile:
      create: yes
      dest: "{{ postgres_base_folder }}/server.conf"
      block: |
        listen_addresses = '*'

  - name: add new configuration to "pg_hba.conf"
    blockinfile:
      dest: "{{ postgres_base_folder }}/pg_hba.conf"
      block: |
        host    all             all             {{ hba_ip_range }}                md5

  - name: Restart the Postgres service
    systemd:
      name: postgresql
      state: restarted
  
  - name: Set postgres database password
    postgresql_user:
      db: postgres
      name: postgres
      password: "{{ postgres_pwd }}"
      role_attr_flags: LOGIN
    become_user: postgres