---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    mount_datavolume: /
    mount_check: false
    postgres_base_folder: /postgresql_data/data
    postgres_installer: /tmp/vmware-postgres-11.7-3.el7.x86_64.rpm
    postgis_installer: /tmp/vmware-postgres-postgis-extension-11.7-3.el7.x86_64.rpm

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: on_create

  - name: Verify if mount is present
    set_fact:
      mount_check: true
    when: item.mount == mount_datavolume
    loop: "{{ ansible_mounts }}"

  - name: Abort script when volume is not mounted
    fail:
      msg: The data volume is not mounted on /postgresql_data. Aborting the Postgres installation.
    when: mount_check == false

  #### START INSTALLING POSTGRES
  - name: Generate folder structure for database
    file:
      state: directory
      path: "{{ postgres_base_folder}}"

  - name: Copy installer files needed
    copy:
      src: "{{ postgres_installer }}"
      dest: /tmp/
      remote_src: no
    become: yes

  - name: Install base rpm VMware Postgres
    yum:
      name: "{{ postgres_installer }}"
      state: present

