---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    mount_datavolume: /
    mount_check: false
    postgres_mount_volume: /postgresql_data
    postgres_base_folder: /postgresql_data/data
    postgres_installer: /tmp/vmware-postgres-11.7-3.el7.x86_64.rpm
    postgis_installer: /tmp/vmware-postgres-postgis-extension-11.7-3.el7.x86_64.rpm
    postgresql_bin_path: 

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: on_create

  - name: Verify if mount is present
    set_fact:
      mount_check: true
    when: item.mount == mount_datavolume
    loop: "{{ ansible_mounts }}"

  - name: Abort script when volume is not mounted
    fail:
      msg: The data volume is not mounted on /postgresql_data. Aborting the Postgres installation.
    when: mount_check == false

  #### START INSTALLING POSTGRES
  - name: Generate folder structure for database
    file:
      state: directory
      path: "{{ postgres_base_folder}}"

  - name: Copy installer files needed
    copy:
      src: "{{ item }}"
      dest: /tmp/
      remote_src: no
    with_items:
      - "{{ postgres_installer }}"
      - "{{ postgis_installer }}"

  - name: Install base rpm VMware Postgres
    yum:
      name: "{{ postgres_installer }}"
      state: present

  - name: Make postgres user owner of postgres_data volume
    file:
      state: directory
      path: "{{ postgres_mount_volume }}"
      owner: postgres
      group: root
      recurse: yes

  - name: Check if PostgreSQL database is initialized.
    stat:
      path: "{{ postgres_base_folder }}/PG_VERSION"
    register: pgdata_dir_version

  - name: Initialize database with correct data path
    command: "/usr/bin/initdb -D {{ postgres_base_folder }}/"
    become_user: postgres
    when: not pgdata_dir_version.stat.exists

  - name: Generate service file & start Postgres
    copy:
      content: |
                [Unit]
                Description=CBS - PostgreSQL database server
                Documentation=man:postgres(1)

                [Service]
                Type=notify
                User=postgres
                ExecStart=/usr/local/pgsql/bin/postgres -D {{ postgres_base_folder }}
                ExecReload=/bin/kill -HUP $MAINPID
                KillMode=mixed
                KillSignal=SIGINT
                TimeoutSec=0

                [Install]
                WantedBy=multi-user.target
      dest: /etc/systemd/system/postgresql.service
