---
- name: Install VMware Postgres
  gather_facts: true
  become: true
  hosts: all
  become: yes
  vars:
    postgres_pwd: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}" #random generated

  tasks:
    - name: Install VMware Postgres
        user:
            name: postgres
            comment: Postgres service account
            state: present
            password: "{{ postgres_pwd }}"
    
    - name: Present randomly generated password
        debug:
            msg: "{{ postgres_pwd }}"