---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    mount_datavolume: /
    mount_check: false
    postgres_mount_volume: /postgresql_data
    postgres_base_folder: /postgresql_data/data
    postgres_installer: /tmp/vmware-postgres-11.7-3.el7.x86_64.rpm
    postgis_installer: /tmp/vmware-postgres-postgis-extension-11.7-3.el7.x86_64.rpm
    postgres_config: /postgresql_data/data/postgresql.conf
    hba_ip_range: "192.168.4.0/24"

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: always

  - name: Verify if mount is present
    set_fact:
      mount_check: true
    when: item.mount == mount_datavolume
    loop: "{{ ansible_mounts }}"

  - name: Abort script when volume is not mounted
    fail:
      msg: The data volume is not mounted on /postgresql_data. Aborting the Postgres installation.
    when: mount_check == false

  #### START INSTALLING POSTGRES
  - name: Install required packages
    yum:
      name: ['python-psycopg2', 'perl', 'perl-Time-HiRes', 'perl-Digest-SHA', 'perl-JSON-PP']
      state: present
      update_cache: true

  - name: Generate folder structure for database
    file:
      state: directory
      path: "{{ postgres_base_folder}}"

  - name: Copy installer files needed
    copy:
      src: "{{ item }}"
      dest: /tmp/
      remote_src: no
    with_items:
      - "{{ postgres_installer }}"
      - "{{ postgis_installer }}"

  - name: Install base rpm VMware Postgres
    yum:
      name: "{{ postgres_installer }}"
      state: present

  - name: Make postgres user owner of postgres_data volume
    file:
      state: directory
      path: "{{ postgres_mount_volume }}"
      owner: postgres
      group: root
      recurse: yes

  - name: Check if PostgreSQL database is initialized.
    stat:
      path: "{{ postgres_base_folder }}/PG_VERSION"
    register: pgdata_dir_version

  - name: Initialize database with correct data path
    command: "/usr/bin/initdb -D {{ postgres_base_folder }}/"
    become_user: postgres
    when: not pgdata_dir_version.stat.exists

  #### CONFIGURE POSTGRES CONFIG FILES
  - name: Generate service file & start Postgres
    copy:
      content: |
                [Unit]
                Description=CBS - PostgreSQL database server
                Documentation=man:postgres(1)
                After=network.target

                [Service]
                Type=forking
                TimeoutSec=120
                User=postgres
                Group=postgres
                
                ExecStart= /usr/bin/pg_ctl -s -D {{ postgres_base_folder }}/ start -w
                ExecReload=/usr/bin/pg_ctl -s -D {{ postgres_base_folder }}/ reload
                ExecStop=  /usr/bin/pg_ctl -s -D {{ postgres_base_folder }}/ stop -m fast
                
                # Due to PostgreSQL's use of shared memory, OOM killer is often overzealous in
                # killing Postgres, so adjust it downward
                OOMScoreAdjust=-200

                [Install]
                WantedBy=multi-user.target
      dest: /etc/systemd/system/postgresql.service

  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive

  - name: Enable Postgres service
    systemd:
      name: postgresql
      enabled: yes
      daemon_reload: yes

  - name: add new configuration to "postgresql.conf"
    blockinfile:
      dest: "{{ postgres_config }}"
      block: |
        include 'server.conf'

  - name: add new configuration to "server.conf"
    blockinfile:
      create: yes
      dest: "{{ postgres_base_folder }}/server.conf"
      block: |
        listen_addresses = '*'

  - name: add new configuration to "pg_hba.conf"
    blockinfile:
      dest: "{{ postgres_base_folder }}/pg_hba.conf"
      block: |
        host    all             all             {{ hba_ip_range }}                md5

  #### TUNE POSTGRES
  # See: https://github.com/melmorabity/ansible-postgresql-tune
  # Download plugin in folder /usr/share/ansible/plugins/modules/

  - name: Tune the database according to specifications given in survey & VM hardware (cpu/memory)
    postgresql_tune:
      harddrive_type: ssd
      db_type: "{{ database_type }}" # desktop dw mixed oltp web # survey
      cpus: "{{ ansible_processor_cores }}" # Ansible fact
      total_memory: "{{ ansible_memtotal_mb }}" # Ansible fact
      connections: "{{ database_connections }}" # Survey
      path: "{{ postgres_config }}"
      backup: True
      os_type: linux
    become_user: postgres

  #### Configure Auditing & logging
  - postgresql_set:
      name: log_destination
      value: csvlog
  - postgresql_set:
      name: logging_collector
      value: on
  - postgresql_set:
      name: log_directory
      value: pg_log
  - postgresql_set:
      name: log_filename
      value: postgresql-%Y-%m-%d_%H%M%S.log
  - postgresql_set:
      name: log_hostname
      value: on
  - postgresql_set:
      name: log_connections
      value: on
  - postgresql_set:
      name: log_line_prefix
      value: '%m [%p]'
  - postgresql_set:
      name: log_statement
      value: all
  - postgresql_set:
      name: log_timezone
      value: UTC+1

  ####
  - name: Restart the Postgres service
    systemd:
      name: postgresql
      state: restarted

  - name: Set postgres db user password
    postgresql_user:
      db: postgres
      name: postgres
      password: "{{ postgres_pwd }}"
      role_attr_flags: LOGIN
    become_user: postgres

  #### INSTALL pgBackRest
  - name: Create directories needed and set permissions
    file:
      dest: "{{ item }}"
      state: directory
      owner: postgres
      group: postgres
    with_items:
      - /etc/pgbackrest
      - /etc/pgbackrest/conf.d
  
  - name: Generate config file for later configuration of pgBackRest
    file:
      dest: /etc/pgbackrest/pgbackrest.conf
      state: touch
      mode: '640'
      owner: postgres
      group: postgres

