---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    mount_datavolume: /postgresql_data

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: on_create
  
  - debug:
        msg: "{{ansible_mounts.mount }}"
    when: "{{ansible_mounts.mount }} != {{ mount_datavolume }}"


  - name: Abort script when volume is not mounted
    meta: end_host
    when: mount_check == false