---
- name: Install VMware Postgres
  gather_facts: yes
  become: yes
  hosts: all
  vars:
    mount_datavolume: /postgresql_data

  tasks:
  - name: Create the Postgres service account
    user:
      name: postgres
      comment: Postgres service account
      state: present
      password: "{{ postgres_pwd | password_hash('sha512') }}"
      update_password: on_create
  
  - name: Verify if Postgres data volume is mounted on the correct path
    meta: end_host
    #msg: "The Postgres data volume is not mounted. Aborting script!"
    with_items: "{{ ansible_mounts }}"
    when: item.mount != mount_datavolume